#Nathan Greenlaw
#Random Testing Quiz
#Makefile

CXX = gcc

SRC1 = testme.c 
SRCS = ${SRC1}

PROG1 = testme
PROGS = ${PROG1}

default: 
	${CXX} -o ${PROGS} ${SRCS}
	./${PROGS}

clean:
	rm -f ${PROGS} *.o *~
